name: Spring Boot CI/CD to AWS EC2

on:
  push:
    branches: ["main"]

jobs:
 build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2️⃣ Setup Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 3️⃣ Give permission to Maven Wrapper
    - name: Grant permission for mvnw
      run: chmod +x mvnw

    # 4️⃣ Build Spring Boot project using Maven
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    # 5️⃣ Copy JAR file to EC2 server
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "target/*.jar"
        target: "/home/ec2-user/app"

    # 6️⃣ Restart Spring Boot application on EC2
    - name: Deploy and Restart App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          echo "Stopping old application..."
          sudo pkill -f java || true

          echo "Starting new application..."
          nohup java -jar /home/ec2-user/app/*.jar \
            > /home/ec2-user/app/app.log 2>&1 < /dev/null &

          echo "Deployment completed!"
